# Generated by Django 3.2.8 on 2021-11-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_ordemservico_datecriacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='numeroSerie',
        ),
    ]
