# Generated by Django 3.2.7 on 2021-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('equipamento', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('largura', models.FloatField()),
                ('lamina', models.IntegerField()),
                ('peso', models.FloatField()),
                ('produto', models.CharField(choices=[('AC', 'Acessório'), ('CC', 'Carregadeira'), ('CD', 'Chapa de desgaste'), ('CB', 'Chock bar'), ('DF', 'Dispositivos e ferramentas'), ('ER', 'Engate rápido'), ('CE', 'Escavadeira'), ('FP', 'Ferramenta de penetração de solo'), ('GA', 'Garfo'), ('CG', 'Graniteira'), ('LA', 'Lâmina'), ('LN', 'Lança'), ('RI', 'Ripper'), ('SG', 'Segmento'), ('VA', 'Vala'), ('SE', 'Serviço')], max_length=2)),
                ('codigoProduto', models.IntegerField()),
                ('dateCriacao', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
