# Generated by Django 3.2.8 on 2021-11-25 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroserie',
            name='dateCriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProdutoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSerie', models.CharField(max_length=30, null=True)),
                ('nomeProduto', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=produtos.models.ProdutoCliente.filePath)),
                ('dateCriacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
            ],
        ),
    ]
