# Generated by Django 3.2.7 on 2021-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='title',
            new_name='nomeProduto',
        ),
    ]
