# Generated by Django 3.2.8 on 2021-11-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20211125_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtocliente',
            old_name='nomeProduto',
            new_name='produto',
        ),
    ]
