# Generated by Django 3.2.7 on 2021-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_title_produto_nomeproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='classeProduto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='lamina',
            new_name='laminaProduto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='largura',
            new_name='larguraProduto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='peso',
            new_name='pesoProduto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='volume',
            new_name='volumeProduto',
        ),
        migrations.AddField(
            model_name='produto',
            name='partNumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='segmentoProduto',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
