# Generated by Django 3.2.7 on 2021-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20210914_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classeProduto',
            field=models.CharField(choices=[('AC', 'Acessório'), ('CC', 'Carregadeira'), ('CD', 'Chapa de desgaste'), ('CB', 'Chock bar'), ('DF', 'Dispositivos e ferramentas'), ('ER', 'Engate rápido'), ('CE', 'Escavadeira'), ('FP', 'Ferramenta de penetração de solo'), ('GA', 'Garfo'), ('CG', 'Graniteira'), ('LA', 'Lâmina'), ('LN', 'Lança'), ('RI', 'Ripper'), ('SG', 'Segmento'), ('VA', 'Vala'), ('SE', 'Serviço')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigoProduto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='equipamento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='laminaProduto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='larguraProduto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nomeProduto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pesoProduto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='volumeProduto',
            field=models.IntegerField(null=True),
        ),
    ]
