# Generated by Django 3.2.7 on 2021-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210914_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='volumeProduto',
            new_name='capacidadeProduto',
        ),
        migrations.AddField(
            model_name='produto',
            name='numDentes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='classeProduto',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigoProduto',
            field=models.CharField(choices=[('AC', 'Acessório'), ('CC', 'Carregadeira'), ('CD', 'Chapa de desgaste'), ('CB', 'Chock bar'), ('DF', 'Dispositivos e ferramentas'), ('ER', 'Engate rápido'), ('CE', 'Escavadeira'), ('FP', 'Ferramenta de penetração de solo'), ('GA', 'Garfo'), ('CG', 'Graniteira'), ('LA', 'Lâmina'), ('LN', 'Lança'), ('RI', 'Ripper'), ('SG', 'Segmento'), ('VA', 'Vala'), ('SE', 'Serviço')], max_length=2, null=True),
        ),
    ]
