# Generated by Django 3.2.7 on 2021-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20210914_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='durezaProduto',
            field=models.CharField(choices=[('GD', 'Geral'), ('HD', 'Pesada'), ('SD', 'Severa'), ('XD', 'Extrema')], max_length=2, null=True),
        ),
    ]
