# Generated by Django 3.2.7 on 2021-09-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_durezaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='segmentoProduto',
            field=models.CharField(choices=[('A', 'Agrícola'), ('C', 'Construção'), ('F', 'Florestal'), ('I', 'Industrial'), ('U', 'Automotiva'), ('M', 'Mineração')], max_length=30, null=True),
        ),
    ]
