# Generated by Django 3.2.8 on 2021-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20211202_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnumber',
            name='terceiro',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
