# Generated by Django 3.2.7 on 2021-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_segmentoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='capacidadeProduto',
            field=models.FloatField(null=True, verbose_name='%2f'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pesoProduto',
            field=models.IntegerField(null=True),
        ),
    ]
