# Generated by Django 3.2.7 on 2021-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20210914_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='larguraProduto',
            field=models.IntegerField(null=True),
        ),
    ]
