# Generated by Django 3.2.7 on 2021-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_larguraproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='capacidadeProduto',
            field=models.FloatField(null=True),
        ),
    ]
