# Generated by Django 3.2.8 on 2021-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_partnumber_partnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='partNumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='partNumber',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
