# Generated by Django 3.2.8 on 2021-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_auto_20211209_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tipoArquivo',
            field=models.CharField(choices=[('M', 'Montagem'), ('P', 'Peça')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
