# Generated by Django 3.2.7 on 2021-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_capacidadeproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='segmentoProduto',
            field=models.CharField(choices=[('Agrícola', 'Agrícola'), ('Construção', 'Construção'), ('Florestal', 'Florestal'), ('Industrial', 'Industrial'), ('Automotivo', 'Automotiva'), ('Mineiração', 'Mineração')], max_length=30, null=True),
        ),
    ]
