# Generated by Django 3.2.7 on 2021-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produto_segmentoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeItem', models.CharField(max_length=30)),
                ('tipoItem', models.CharField(max_length=20)),
                ('partNumber', models.CharField(max_length=16)),
                ('tipoFabricacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='partNumber',
        ),
        migrations.AlterField(
            model_name='produto',
            name='classeProduto',
            field=models.CharField(choices=[('6 SW', '6 SW'), ('6 LH', '6 LH'), ('7 SW', '7 SW'), ('7 LH', '7 LH'), ('7S SW', '7S SW'), ('7S LH', '7S LH'), ('8 SW', '8 SW'), ('8 LH', '8 LH'), ('9 SW', '9 SW'), ('9 LH', '9 LH'), ('9S SW', '9S SW'), ('9S LH', '9S LH')], max_length=5, null=True),
        ),
    ]
