# Generated by Django 3.2.8 on 2021-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_partnumber_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='tipoArquivo',
            field=models.CharField(choices=[('M', 'Montagem'), ('P', 'Peça')], max_length=8),
        ),
    ]
