# Generated by Django 3.2.8 on 2021-12-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_arquivo_tipoarquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='partNumber',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.arquivo', unique=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='partNumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', unique=True),
        ),
    ]
