# Generated by Django 3.2.7 on 2021-09-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_auto_20210917_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nomeItem',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tipoItem',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='capacidadeProduto',
            new_name='capacidade',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='classeProduto',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='codigoProduto',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='durezaProduto',
            new_name='dureza',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='laminaProduto',
            new_name='lamina',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='larguraProduto',
            new_name='largura',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nomeProduto',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='pesoProduto',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='segmentoProduto',
            new_name='segmento',
        ),
    ]
