# Generated by Django 3.2.8 on 2021-12-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_auto_20211216_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnumber',
            name='produto',
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='arquivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.arquivo'),
        ),
    ]
