# Generated by Django 3.2.7 on 2021-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_auto_20210924_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='numeroSerie',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
