# Generated by Django 3.2.8 on 2021-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_alter_partnumber_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='partNumber',
            field=models.CharField(max_length=30),
        ),
    ]
