# Generated by Django 3.2.7 on 2021-09-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_produto_numeroserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='produto',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
            preserve_default=False,
        ),
    ]
