# Generated by Django 3.2.7 on 2021-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_auto_20210929_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='partNumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='revisao',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipoFabricacao',
            field=models.CharField(choices=[('Montagem Geral', 'Montagem Geral'), ('Montagem', 'Montagem'), ('Usinagem', 'Usinagem'), ('Soldado', 'Conjunto Soldado'), ('CNC', 'Corte CNC'), ('CNC / Dobra', 'Corte CNC com Dobra'), ('CNC / Usinagem', 'Corte CNC com Usinagem'), ('CNC / Dobra / Usinagem', 'Corte CNC com Dobra e Usinagem'), ('Manual', 'Corte Manual'), ('Manual / Dobra', 'Corte Manual com Dobra'), ('Manual / Usinagem', 'Corte Manual com Usinagem'), ('Manual / Dobra / Usinagem', 'Corte Manual com Dobra e Usinagem')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('DWG', 'DWG'), ('DXF', 'DXF'), ('eDRA', 'eDrawing'), ('PDF', 'PDF')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='revisao',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('Peça', 'Peça'), ('Montagem', 'Montagem'), ('Drawing', 'Drawing')], max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipoFabricacao',
            field=models.CharField(choices=[('Montagem Geral', 'Montagem Geral'), ('Montagem', 'Montagem'), ('Usinagem', 'Usinagem'), ('Soldado', 'Conjunto Soldado'), ('CNC', 'Corte CNC'), ('CNC / Dobra', 'Corte CNC com Dobra'), ('CNC / Usinagem', 'Corte CNC com Usinagem'), ('CNC / Dobra / Usinagem', 'Corte CNC com Dobra e Usinagem'), ('Manual', 'Corte Manual'), ('Manual / Dobra', 'Corte Manual com Dobra'), ('Manual / Usinagem', 'Corte Manual com Usinagem'), ('Manual / Dobra / Usinagem', 'Corte Manual com Dobra e Usinagem')], max_length=25),
        ),
    ]
