# Generated by Django 3.2.7 on 2021-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_auto_20210929_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='revisao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='revisao',
            field=models.IntegerField(null=True),
        ),
    ]
