# Generated by Django 3.2.8 on 2021-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_alter_partnumber_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='partNumber',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
