# Generated by Django 3.2.8 on 2021-12-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_alter_partnumber_partnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnumber',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='partnumber',
            name='produto',
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='partNumber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.partnumber'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='partNumber',
            field=models.CharField(max_length=30),
        ),
    ]
