# Generated by Django 3.2.7 on 2021-09-30 16:54

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_alter_item_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(default=1, upload_to=produtos.models.Item.filePath),
            preserve_default=False,
        ),
    ]
