# Generated by Django 3.2.7 on 2021-09-30 17:25

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_item_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='file',
            field=models.FileField(default=1, upload_to=produtos.models.Arquivo.filePath),
            preserve_default=False,
        ),
    ]
