# Generated by Django 3.2.8 on 2021-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_partnumber_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='classeproduto',
            name='nome',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nome',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
