# Generated by Django 3.2.8 on 2022-01-10 12:28

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_auto_20211227_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocliente',
            name='file',
            field=models.FileField(null=True, upload_to=produtos.models.ProdutoCliente.filePath),
        ),
    ]
