# Generated by Django 3.2.7 on 2021-10-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_alter_arquivo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dateUpdate',
        ),
    ]
