# Generated by Django 3.2.8 on 2022-01-10 13:50

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_alter_produtocliente_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocliente',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=produtos.models.ProdutoCliente.filePath),
        ),
    ]
