# Generated by Django 3.2.8 on 2022-01-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_alter_produtocliente_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocliente',
            name='numeroSerie',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
