# Generated by Django 3.2.7 on 2021-10-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_remove_item_dateupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='dateUpdate',
        ),
    ]
