# Generated by Django 3.2.8 on 2021-10-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_alter_item_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(max_length=8),
        ),
    ]
