# Generated by Django 3.2.8 on 2021-10-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_alter_item_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='classe',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='dureza',
            new_name='classeAplicacao',
        ),
    ]
