# Generated by Django 3.2.8 on 2021-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0029_auto_20211029_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSerie', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='numeroSerie',
        ),
    ]
