# Generated by Django 3.2.8 on 2021-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0030_auto_20211101_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialnumber',
            name='numeroSerie',
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='nome',
            field=models.CharField(default=21, max_length=30),
            preserve_default=False,
        ),
    ]
