# Generated by Django 3.2.8 on 2021-11-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0031_auto_20211101_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.AddField(
            model_name='produto',
            name='numeroSerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.numeroserie'),
        ),
    ]
