# Generated by Django 3.2.8 on 2021-11-03 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0032_auto_20211101_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroserie',
            name='nome',
        ),
        migrations.AddField(
            model_name='numeroserie',
            name='serialNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
