# Generated by Django 3.2.8 on 2021-11-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0033_auto_20211103_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='revisao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='revisao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='capacidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(choices=[('AC', 'Acessório'), ('CC', 'Carregadeira'), ('CD', 'Chapa de desgaste'), ('CB', 'Chock bar'), ('DF', 'Dispositivos e ferramentas'), ('ER', 'Engate rápido'), ('CE', 'Escavadeira'), ('FP', 'Ferramenta de penetração de solo'), ('GA', 'Garfo'), ('CG', 'Graniteira'), ('LA', 'Lâmina'), ('LN', 'Lança'), ('RI', 'Ripper'), ('SG', 'Segmento'), ('VA', 'Vala'), ('SE', 'Serviço')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='equipamento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lamina',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='largura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='segmento',
            field=models.CharField(choices=[('A', 'Agrícola'), ('C', 'Construção'), ('F', 'Florestal'), ('I', 'Industrial'), ('U', 'Automotiva'), ('M', 'Mineração')], max_length=30),
        ),
    ]
