# Generated by Django 3.2.8 on 2021-11-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0004_remove_ordemservico_numeroserie'),
        ('produtos', '0034_auto_20211104_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroserie',
            name='os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workOrder.ordemservico', unique=True),
            preserve_default=False,
        ),
    ]
