# Generated by Django 3.2.8 on 2021-11-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0035_numeroserie_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numeroSerie',
        ),
        migrations.AddField(
            model_name='numeroserie',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', unique=True),
            preserve_default=False,
        ),
    ]
