# Generated by Django 3.2.8 on 2021-11-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0004_remove_ordemservico_numeroserie'),
        ('produtos', '0038_auto_20211105_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroserie',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workOrder.ordemservico'),
        ),
        migrations.AlterField(
            model_name='numeroserie',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
