# Generated by Django 3.2.8 on 2021-11-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0039_auto_20211105_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='lamina',
            new_name='espessura',
        ),
    ]
