# Generated by Django 3.2.8 on 2021-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0041_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descontinuado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
