# Generated by Django 3.2.8 on 2021-11-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colaborator.colaborador')),
            ],
        ),
    ]
