# Generated by Django 3.2.7 on 2021-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='nomeCompleto',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='apelido',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sobrenome',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
