# Generated by Django 3.2.8 on 2021-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
