# Generated by Django 3.2.7 on 2021-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborator', '0002_auto_20211001_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
