# Generated by Django 3.2.8 on 2021-10-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('colaborator', '0003_auto_20211005_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='departamento',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='departments.departamento'),
            preserve_default=False,
        ),
    ]
